version: 2.1

orbs:
  architect: giantswarm/architect@0.10.1

workflows:
  test:
    jobs:
      - architect/go-test:
          name: go-test
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/

      - architect/integration-test:
          name: integration-test-basic
          test-dir: "integration/test/basic"
          requires:
            - go-test
